"""Stable identity placeholders and current-name rendering."""

from .domain import (
    CHARACTER_PLACEHOLDER,
    IDENTITY_MODE_LITERAL,
    IDENTITY_MODE_RENDER,
    IDENTITY_MODE_TEMPLATE,
    IDENTITY_MODES,
    IDENTITY_REFERENCE_GUIDANCE,
    PRIVATE_USER_PLACEHOLDER,
    IdentityAnnotationCandidate,
    IdentityCatalog,
    IdentityParticipant,
    IdentityRenderContext,
    IdentityTemplate,
    build_identity_catalog,
    decode_model_identity_text,
    decode_model_parameter_map,
    encode_identity_template_for_model,
    escape_untrusted_identity_syntax,
    group_user_placeholder,
    identity_annotation_candidates,
    internal_identity_placeholders,
    project_identity_text_for_model,
    render_identity_text,
    render_model_identity_text,
    resolve_private_display_name,
    validate_identity_template,
)
from .service import IdentityService

__all__ = [
    "CHARACTER_PLACEHOLDER",
    "IDENTITY_REFERENCE_GUIDANCE",
    "IDENTITY_MODE_LITERAL",
    "IDENTITY_MODE_RENDER",
    "IDENTITY_MODE_TEMPLATE",
    "IDENTITY_MODES",
    "PRIVATE_USER_PLACEHOLDER",
    "IdentityAnnotationCandidate",
    "IdentityCatalog",
    "IdentityParticipant",
    "IdentityRenderContext",
    "IdentityService",
    "IdentityTemplate",
    "build_identity_catalog",
    "decode_model_identity_text",
    "decode_model_parameter_map",
    "encode_identity_template_for_model",
    "escape_untrusted_identity_syntax",
    "group_user_placeholder",
    "identity_annotation_candidates",
    "internal_identity_placeholders",
    "project_identity_text_for_model",
    "render_identity_text",
    "resolve_private_display_name",
    "render_model_identity_text",
    "validate_identity_template",
]
