"""Public pure-domain contract for versioned player profiles."""

from .commands import (
    AddProfileEntry,
    ProfileCommand,
    ProfileCommandReceipt,
    ProfileMutationKind,
    ProfileMutationOutcome,
    ProfileMutationResult,
    RestoreProfileEntry,
    ReviseProfileEntry,
    WithdrawProfileEntry,
    apply_profile_command,
    command_fingerprint,
    replay_profile_command,
)
from .domain import (
    PlayerProfileEntry,
    PlayerProfileScope,
    PlayerProfileSnapshot,
    ProfileAdminEvidence,
    ProfileCategory,
    ProfileEntryDraft,
    ProfileEntryStatus,
    ProfileEvidence,
    ProfileInputModality,
    ProfileLayer,
    ProfileMessageEvidence,
    ProfileSensitivity,
    ProfileSourceType,
)
from .errors import (
    PlayerProfileError,
    ProfileConflictError,
    ProfileErrorCode,
    ProfileValidationError,
)
from .ports import PlayerProfileReader
from .projection import (
    MAX_PROJECTED_ENTRY_TEXT_CHARS,
    PlayerProfileProjection,
    PlayerProfileProjectionRequest,
    ProjectedProfileEntry,
    build_compact_projection,
)

__all__ = [
    "MAX_PROJECTED_ENTRY_TEXT_CHARS",
    "AddProfileEntry",
    "PlayerProfileEntry",
    "PlayerProfileError",
    "PlayerProfileProjection",
    "PlayerProfileProjectionRequest",
    "PlayerProfileReader",
    "PlayerProfileScope",
    "PlayerProfileSnapshot",
    "ProfileAdminEvidence",
    "ProfileCategory",
    "ProfileCommand",
    "ProfileCommandReceipt",
    "ProfileConflictError",
    "ProfileEntryDraft",
    "ProfileEntryStatus",
    "ProfileEvidence",
    "ProfileErrorCode",
    "ProfileInputModality",
    "ProfileLayer",
    "ProfileMessageEvidence",
    "ProfileMutationKind",
    "ProfileMutationOutcome",
    "ProfileMutationResult",
    "ProfileSensitivity",
    "ProfileSourceType",
    "ProfileValidationError",
    "ProjectedProfileEntry",
    "ReviseProfileEntry",
    "RestoreProfileEntry",
    "WithdrawProfileEntry",
    "apply_profile_command",
    "build_compact_projection",
    "command_fingerprint",
    "replay_profile_command",
]
