"""Persistence boundary for sticker admission, collection, and administration."""

from typing import Any, Protocol


class StickerRepositoryReadPort(Protocol):
    """Queries used by the sticker feature and its presentation surfaces."""

    async def count_sticker_items_since(self, *args: object, **kwargs: object) -> Any: ...
    async def get_sticker_candidate(self, *args: object, **kwargs: object) -> Any: ...
    async def get_sticker_candidate_by_source_asset(
        self, *args: object, **kwargs: object
    ) -> Any: ...
    async def get_sticker_config(self, *args: object, **kwargs: object) -> Any: ...
    async def get_sticker_asset(self, *args: object, **kwargs: object) -> Any: ...
    async def get_accessible_sticker_asset(self, *args: object, **kwargs: object) -> Any: ...
    async def get_sticker_item(self, *args: object, **kwargs: object) -> Any: ...
    async def find_sticker_item_by_sha(self, *args: object, **kwargs: object) -> Any: ...
    async def preflight_sticker_visual_capacity(self, *args: object, **kwargs: object) -> Any: ...
    async def get_sticker_trigger_state(self, *args: object, **kwargs: object) -> Any: ...
    async def get_sticker_intake_session(self, *args: object, **kwargs: object) -> Any: ...
    async def get_active_sticker_intake_session(self, *args: object, **kwargs: object) -> Any: ...
    async def get_sticker_intake_entry(self, *args: object, **kwargs: object) -> Any: ...
    async def get_sticker_intake_entry_by_client_id(
        self, *args: object, **kwargs: object
    ) -> Any: ...
    async def find_sticker_intake_entry_by_sha(self, *args: object, **kwargs: object) -> Any: ...
    async def list_expired_sticker_intake_sessions(
        self, *args: object, **kwargs: object
    ) -> Any: ...
    async def list_sticker_intake_entries(self, *args: object, **kwargs: object) -> Any: ...
    async def get_character_identity_reference(self, *args: object, **kwargs: object) -> Any: ...
    async def list_sticker_checks(self, *args: object, **kwargs: object) -> Any: ...
    async def list_sticker_candidates(self, *args: object, **kwargs: object) -> Any: ...
    async def list_sticker_items(self, *args: object, **kwargs: object) -> Any: ...
    async def page_sticker_candidates(self, *args: object, **kwargs: object) -> Any: ...
    async def page_sticker_checks(self, *args: object, **kwargs: object) -> Any: ...
    async def page_sticker_items(self, *args: object, **kwargs: object) -> Any: ...
    async def search_sticker_items_indexed(self, *args: object, **kwargs: object) -> Any: ...
    async def sticker_recent_run_usage(self, *args: object, **kwargs: object) -> Any: ...
    async def sticker_recent_usage_stats(self, *args: object, **kwargs: object) -> Any: ...
    async def sticker_stats(self, *args: object, **kwargs: object) -> Any: ...
    async def sticker_inventory_summary(self, *args: object, **kwargs: object) -> Any: ...
    async def quick_setup_sticker_inventory(self, *args: object, **kwargs: object) -> Any: ...
    async def resolve_sticker_run_refs(self, *args: object, **kwargs: object) -> Any: ...


class StickerRepositoryWritePort(Protocol):
    """Mutations used by the sticker feature and its administration surfaces."""

    async def admin_accept_sticker_candidate(self, *args: object, **kwargs: object) -> Any: ...
    async def cleanup_sticker_capacity(self, *args: object, **kwargs: object) -> Any: ...
    async def clear_sticker_instance_data(self, *args: object, **kwargs: object) -> Any: ...
    async def complete_sticker_collection_task(self, *args: object, **kwargs: object) -> Any: ...
    async def replace_character_identity_reference(
        self, *args: object, **kwargs: object
    ) -> Any: ...
    async def create_sticker_candidate(self, *args: object, **kwargs: object) -> Any: ...
    async def create_sticker_asset(self, *args: object, **kwargs: object) -> Any: ...
    async def create_sticker_run_refs(self, *args: object, **kwargs: object) -> Any: ...
    async def defer_sticker_collection_task(self, *args: object, **kwargs: object) -> Any: ...
    async def delete_character_identity_reference(self, *args: object, **kwargs: object) -> Any: ...
    async def delete_sticker_candidate(self, *args: object, **kwargs: object) -> Any: ...
    async def disable_sticker_item_for_instance(self, *args: object, **kwargs: object) -> Any: ...
    async def mark_media_asset_release_pending(self, *args: object, **kwargs: object) -> Any: ...
    async def mark_sticker_candidate_waiting_check(
        self, *args: object, **kwargs: object
    ) -> Any: ...
    async def mark_stickers_for_persona_review(self, *args: object, **kwargs: object) -> Any: ...
    async def quarantine_sticker_candidate(self, *args: object, **kwargs: object) -> Any: ...
    async def record_sticker_check(self, *args: object, **kwargs: object) -> Any: ...
    async def record_sticker_usage(self, *args: object, **kwargs: object) -> Any: ...
    async def reinforce_sticker_item(self, *args: object, **kwargs: object) -> Any: ...
    async def replace_sticker_candidate_source(self, *args: object, **kwargs: object) -> Any: ...
    async def set_sticker_candidate_checking(self, *args: object, **kwargs: object) -> Any: ...
    async def set_sticker_item_status(self, *args: object, **kwargs: object) -> Any: ...
    async def update_sticker_config(self, *args: object, **kwargs: object) -> Any: ...
    async def update_sticker_configs_atomically(self, *args: object, **kwargs: object) -> Any: ...
    async def update_sticker_item_description(self, *args: object, **kwargs: object) -> Any: ...
    async def update_sticker_trigger_state(self, *args: object, **kwargs: object) -> Any: ...
    async def wake_waiting_sticker_checks(self, *args: object, **kwargs: object) -> Any: ...


class StickerIntakeRepositoryWritePort(Protocol):
    """Mutations owned by one recoverable quick-intake batch."""

    async def create_sticker_intake_session(self, *args: object, **kwargs: object) -> Any: ...
    async def add_sticker_intake_entry(self, *args: object, **kwargs: object) -> Any: ...
    async def attach_sticker_intake_upload(self, *args: object, **kwargs: object) -> Any: ...
    async def seal_sticker_intake_upload_session(self, *args: object, **kwargs: object) -> Any: ...
    async def claim_sticker_intake_upload_content(self, *args: object, **kwargs: object) -> Any: ...
    async def set_sticker_intake_task(self, *args: object, **kwargs: object) -> Any: ...
    async def mark_sticker_intake_entry_analyzing(self, *args: object, **kwargs: object) -> Any: ...
    async def stage_sticker_intake_candidate(self, *args: object, **kwargs: object) -> Any: ...
    async def settle_sticker_intake_entry(self, *args: object, **kwargs: object) -> Any: ...
    async def set_sticker_intake_entry_selected(self, *args: object, **kwargs: object) -> Any: ...
    async def sticker_intake_accepts_results(self, *args: object, **kwargs: object) -> Any: ...
    async def set_sticker_intake_review(self, *args: object, **kwargs: object) -> Any: ...
    async def retry_sticker_intake_entry(self, *args: object, **kwargs: object) -> Any: ...
    async def fail_sticker_intake_session(self, *args: object, **kwargs: object) -> Any: ...
    async def freeze_sticker_intake_session(self, *args: object, **kwargs: object) -> Any: ...
    async def complete_sticker_intake_session(self, *args: object, **kwargs: object) -> Any: ...
    async def expire_sticker_intake_sessions(self, *args: object, **kwargs: object) -> Any: ...
    async def mark_sticker_intake_entry_imported(self, *args: object, **kwargs: object) -> Any: ...


class StickerRepositoryPort(
    StickerRepositoryReadPort,
    StickerRepositoryWritePort,
    StickerIntakeRepositoryWritePort,
    Protocol,
):
    """Complete current sticker persistence boundary."""


__all__ = [
    "StickerIntakeRepositoryWritePort",
    "StickerRepositoryPort",
    "StickerRepositoryReadPort",
    "StickerRepositoryWritePort",
]
