"""Frozen product limits for the Timer domain."""

MIN_ABSOLUTE_LEAD_SECONDS = 60
MAX_ABSOLUTE_HORIZON_SECONDS = 10 * 365 * 24 * 60 * 60
MIN_RELATIVE_DELAY_SECONDS = 60
MAX_RELATIVE_DELAY_SECONDS = 365 * 24 * 60 * 60

MAX_PROMPT_CHARS = 1000
MAX_PROFILE_ID_CHARS = 128
MAX_INSTANCE_ID_CHARS = 256
MAX_INTERNAL_REF_CHARS = 128
MAX_IDEMPOTENCY_KEY_CHARS = 160
MAX_SOURCE_REFS = 16

MAX_CREATE_ACTIONS_PER_RUN = 3
MAX_MANAGE_ACTIONS_PER_RUN = 5
MAX_NONTERMINAL_RULES_PER_INSTANCE = 128
MAX_NONTERMINAL_OCCURRENCES_PER_INSTANCE = 256

MAX_LIST_RESULTS = 64
MAX_SEMANTIC_CANDIDATES = 12
MAX_CANDIDATE_PREVIEW_CHARS = 200
MAX_CANDIDATE_REASON_CHARS = 240
MAX_CANDIDATE_EVIDENCE_REFS = 8

__all__ = [name for name in globals() if name.startswith("MAX_") or name.startswith("MIN_")]
