"""Narrow persistence boundaries used by Main Core orchestration."""

from datetime import datetime
from typing import Any, Protocol

from ...contracts.group_flow import GroupReplyRelocationCheck, GroupReplyRelocationResult
from ...contracts.main_core import MainCoreHandlePort


class MainCoreQueryPort(Protocol):
    async def list_instance_runs(self, *args: object, **kwargs: object) -> Any: ...


class CoreResultPort(Protocol):
    async def commit_instance_core_result(self, *args: object, **kwargs: object) -> object: ...
    async def start_work_recovery_run(self, *args: object, **kwargs: object) -> object: ...


class RuntimeCleanupPort(Protocol):
    async def clear_profile_runtime(self, *args: object, **kwargs: object) -> object: ...
    async def reset_character_instance_runtime(self, *args: object, **kwargs: object) -> object: ...


class GroupReplyRelocationPort(Protocol):
    async def apply_reply_relocation(
        self,
        check: GroupReplyRelocationCheck,
        *,
        now: datetime,
    ) -> GroupReplyRelocationResult: ...


class MainCoreTimelinePort(Protocol):
    async def get_profile_timezone(self, *args: object, **kwargs: object) -> object: ...
    async def get_state_message_gate_policy(self, *args: object, **kwargs: object) -> object: ...
    async def get_state_message_gate_snapshot(self, *args: object, **kwargs: object) -> object: ...
    async def resolve_contact_policy(self, *args: object, **kwargs: object) -> object: ...
    async def resolve_expression_pacing_policy(self, *args: object, **kwargs: object) -> object: ...
    async def start_instance_run(self, *args: object, **kwargs: object) -> object: ...
    async def finish_instance_run(self, *args: object, **kwargs: object) -> object: ...
    async def bind_instance_run_workflow(self, *args: object, **kwargs: object) -> object: ...
    async def get_instance_run_workflow(self, *args: object, **kwargs: object) -> object: ...
    async def get_previous_instance_run_context_message_ids(
        self, *args: object, **kwargs: object
    ) -> object: ...
    async def schedule_instance_wakeup(self, *args: object, **kwargs: object) -> object: ...
    async def list_world_lore_entries(self, *args: object, **kwargs: object) -> object: ...
    async def get_world_lore_entry(self, *args: object, **kwargs: object) -> object: ...
    async def list_character_intents(self, *args: object, **kwargs: object) -> object: ...
    async def settle_contact_evidence(self, *args: object, **kwargs: object) -> object: ...
    async def finalize_contact_attempt(self, *args: object, **kwargs: object) -> object: ...


__all__ = [
    "CoreResultPort",
    "GroupReplyRelocationPort",
    "MainCoreHandlePort",
    "MainCoreQueryPort",
    "MainCoreTimelinePort",
    "RuntimeCleanupPort",
]
