"""Persistence boundary for web provider configuration and research records."""

from typing import Any, Protocol

from ...contracts.ai_models import AICapabilityRequest, AICapabilityResult
from .domain import WebImageSearchResultRecord, WebPageSnapshotRecord, WebSearchResultRecord


class WebAIManagerPort(Protocol):
    async def invoke_capability(self, request: AICapabilityRequest) -> AICapabilityResult: ...


class WebRepositoryPort(Protocol):
    async def archive_web_search_provider(self, *args: object, **kwargs: object) -> Any: ...
    async def count_web_search_sessions(self, *args: object, **kwargs: object) -> int: ...
    async def get_web_search_provider(self, *args: object, **kwargs: object) -> Any: ...
    async def list_web_search_providers(self, *args: object, **kwargs: object) -> Any: ...
    async def list_web_search_sessions(self, *args: object, **kwargs: object) -> Any: ...
    async def get_web_search_session(self, *args: object, **kwargs: object) -> Any: ...
    async def get_web_search_result(self, *args: object, **kwargs: object) -> Any: ...
    async def get_web_image_result(self, *args: object, **kwargs: object) -> Any: ...
    async def get_web_page_snapshot(self, *args: object, **kwargs: object) -> Any: ...
    async def set_web_search_provider_enabled(self, *args: object, **kwargs: object) -> Any: ...
    async def update_web_search_settings(self, *args: object, **kwargs: object) -> Any: ...
    async def upsert_web_search_provider(self, *args: object, **kwargs: object) -> Any: ...
    async def create_web_search_session(self, *args: object, **kwargs: object) -> Any: ...
    async def complete_web_search_session(self, *args: object, **kwargs: object) -> Any: ...
    async def save_web_search_results(
        self,
        profile_id: str,
        instance_id: str,
        session_id: str,
        results: list[WebSearchResultRecord],
    ) -> list[WebSearchResultRecord]: ...
    async def save_web_image_results(
        self,
        profile_id: str,
        instance_id: str,
        session_id: str,
        results: list[WebImageSearchResultRecord],
    ) -> list[WebImageSearchResultRecord]: ...
    async def upsert_web_page_snapshot(
        self, snapshot: WebPageSnapshotRecord
    ) -> WebPageSnapshotRecord: ...
