from __future__ import annotations

from .command_protocol_types import CommandParameter, CommandSpec
from .command_string_values import boolean_validator, integer_validator, reference_validator

_RESULT_FIELD_NAMES = {
    "query": "查询",
    "question": "想知道什么",
    "link": "链接",
    "intended_use": "打算怎么用",
    "purpose": "用途",
    "focus": "关注内容",
    "depth": "搜索深度",
    "freshness": "时间范围",
    "resource_ids": "资料引用",
    "resource_id": "资料引用",
    "image_resource_ids": "图片引用",
    "image_resource_id": "图片引用",
    "asset_ref_id": "资源引用",
    "asset_ref": "图片引用",
    "source_ref": "来源引用",
    "sticker_ref": "表情引用",
    "sticker_import_source_refs": "表情候选来源引用",
    "message_ref": "消息引用",
    "member_ref": "人物引用",
    "evidence_ref": "依据",
    "profile_entry_ref": "认识引用",
    "profile_entry_refs": "认识引用",
    "original_impression": "原来的印象",
    "new_impression": "改成",
    "impression": "印象",
    "reason": "原因",
    "operation": "操作",
    "limit": "数量",
    "text": "内容",
    "time_expression": "时间",
    "action_text": "到时候做什么",
    "change": "怎么改",
    "brief": "简述",
    "ultra_brief": "极简描述",
    "keywords": "关键词",
    "importance": "重要度",
    "name": "名称",
    "definition": "定义",
    "aliases": "别名",
    "trigger_keywords": "触发词",
    "category": "类别",
    "change_reason": "变更原因",
    "strength": "强度",
    "file_format": "文件格式",
    "display_name": "显示名称",
    "audience": "目标读者",
    "requirements": "必须覆盖",
    "source_materials": "素材与事实来源",
    "voice": "语气与作者口吻",
    "fact_policy": "事实边界",
    "image_asset_ids": "图片引用",
    "layout_preference": "版式取向",
    "enabled": "是否启用",
    "delay_minutes": "延迟分钟",
    "due_at": "执行时间",
    "intent_kind": "安排类型",
    "schedule_ref": "安排引用",
    "start_at": "开始时间",
    "end_at": "结束时间",
    "output_type": "图片类型",
    "counterpart_requirements": "对方本轮画面要求",
    "scene": "画面",
    "scene_plan": "完整画面方案",
    "selected_visual_facts": "选定画面事实",
    "aspect_ratio": "宽高比",
    "size": "尺寸",
    "image_count": "图片数量",
    "reference_asset_ids": "参考图片",
    "reference_purposes": "逐张参考用途",
    "reference_images": "参考图片",
    "animation_position": "动图位置",
    "interface": "界面",
    "must_include": "一定要有",
    "materials": "用到的材料",
    "audience_and_tone": "给谁看、希望是什么感觉",
    "timer_ref": "计时器引用",
    "results": "结果",
    "pages": "正文",
    "stickers": "表情",
    "timers": "计时器",
    "candidates": "候选项",
    "frames": "图像帧",
    "title": "标题",
    "domain": "来源站点",
    "shareable_url": "网址",
    "snippet": "摘要",
    "published_at": "发布时间",
    "partial_warning": "部分结果提示",
    "description": "描述",
    "emotion": "情绪",
    "speech_act": "表达用途",
    "intensity": "强度",
    "recently_used": "近期用过",
    "content": "正文",
    "truncated": "是否截断",
    "message": "说明",
    "error": "错误",
    "prompt": "内容",
    "prompt_preview": "内容预览",
    "target": "对象",
    "rule_kind": "规则类型",
    "action": "操作",
    "source_mime_type": "原图类型",
    "source_width": "原图宽度",
    "source_height": "原图高度",
    "source_frame_count": "原图帧数",
    "source_frame_index": "帧序号",
    "width": "宽度",
    "height": "高度",
    "mime_type": "图像类型",
    "notice": "提示",
    "period_start": "开始时间",
    "period_end": "结束时间",
    "story": "经历",
    "current_state": "当时状态",
    "lore_id": "世界资料引用",
    "lore_ids": "世界资料引用",
}

_MODEL_RESULT_VALUES = {
    "ADD": "新增",
    "REVISE": "修正",
    "WITHDRAW": "撤回",
    "DECLARED_FACT": "对方明确陈述",
    "INFERRED_OBSERVATION": "根据交流观察",
    "DIRECT_STATEMENT": "直接陈述",
    "STRONG_TEXT_EVIDENCE": "明确文字证据",
    "DIRECT_CORRECTION": "直接纠正",
    "NORMAL": "普通",
    "PRIVATE": "私密",
    "SENSITIVE": "敏感",
    "ANSWER_USER": "核实当前交流",
    "SELF_EXPLORATION": "自主探索",
    "auto": "自动",
    "quick": "快速",
    "balanced": "均衡",
    "deep": "深入",
    "day": "一天内",
    "week": "一周内",
    "month": "一月内",
    "year": "一年内",
    "any": "不限时间",
    "ABSOLUTE": "绝对时间",
    "RELATIVE": "延迟触发",
    "WEEKLY": "每周重复",
    "YEARLY": "每年重复",
    "SERIES": "整个系列",
    "OCCURRENCE": "单次触发",
    "PAUSE": "暂停",
    "RESUME": "恢复",
    "CANCEL": "取消",
    "AUTO": "自动",
    "REPORT": "报告",
    "EDITORIAL": "编辑排版",
    "DATA_BRIEF": "数据简报",
}

_DELAY_PARAMETER = CommandParameter(
    "延迟",
    "delay_seconds",
    prompt_hint="上一发送或撤回完成后等待 0 至 120 秒；默认 0",
    validator=integer_validator("延迟", minimum=0, maximum=120),
)

_INTERRUPTIBLE_PARAMETER = CommandParameter(
    "可被打断",
    "interruptible",
    choices=("是", "否"),
    prompt_hint="默认是",
    validator=boolean_validator("可被打断"),
)

_MEMO_PARAMETER = CommandParameter(
    "留话",
    "memo",
    prompt_hint="见本区开头规则",
    identity_mode="template",
)

_RETRACTION_DELAY_PARAMETER = CommandParameter(
    "延迟",
    "delay_seconds",
    prompt_hint="撤回前等待多少秒，0 至 120；默认 0",
    validator=integer_validator("延迟", minimum=0, maximum=120),
)


_TERMINAL_SPECS = (
    CommandSpec(
        "发文字",
        "__send_text",
        "想说话、回应、搭腔、吐槽或主动找人时使用；一个指令就是一条独立消息。",
        (
            CommandParameter(
                "内容",
                "content",
                required=True,
                prompt_hint="对方会看到的文字",
                identity_mode="template",
            ),
            CommandParameter(
                "语音",
                "as_voice",
                choices=("是", "否"),
                prompt_hint="想用语音说这段内容时填“是”；不填或填“否”就发送文字",
                validator=boolean_validator("语音"),
            ),
            CommandParameter(
                "回复",
                "reply_ref",
                prompt_hint="当前可见的一条消息短引用",
                validator=reference_validator("回复"),
            ),
            CommandParameter(
                "提及",
                "mention_refs",
                prompt_hint="当前可见的一个或多个人物短引用",
                validator=reference_validator("提及", multiple=True),
            ),
            _DELAY_PARAMETER,
            _INTERRUPTIBLE_PARAMETER,
            _MEMO_PARAMETER,
        ),
        terminal=True,
        send_kind="TEXT",
        usage_guidance=(
            "多条消息就按顺序写多个指令。[[延迟]]用于交流节奏，整批发送与撤回合计最多 300 秒。"
            "[[可被打断]]为“是”时，新消息可在该条发送前中止后续表达；“否”仍发送。"
        ),
    ),
    CommandSpec(
        "发图片",
        "__send_image",
        "想把已经拿到、刚生成或对方发来的某张图片发出去时使用。",
        (
            CommandParameter(
                "图片",
                "asset_ref",
                required=True,
                prompt_hint="当前可用的图片短引用",
                validator=reference_validator("图片"),
            ),
            CommandParameter(
                "回复",
                "reply_ref",
                prompt_hint="当前可见的一条消息短引用",
                validator=reference_validator("回复"),
            ),
            CommandParameter(
                "提及",
                "mention_refs",
                prompt_hint="当前可见的一个或多个人物短引用",
                validator=reference_validator("提及", multiple=True),
            ),
            _DELAY_PARAMETER,
            _INTERRUPTIBLE_PARAMETER,
            _MEMO_PARAMETER,
        ),
        terminal=True,
        send_kind="IMAGE",
        usage_guidance="只能填写当前已有的图片短引用；确实需要原图细节时先用“看清这张图”。",
    ),
    CommandSpec(
        "发表情",
        "__send_sticker",
        "想用当前已经找到或收藏的表情回应时使用。",
        (
            CommandParameter(
                "表情",
                "asset_ref",
                required=True,
                prompt_hint="当前可用的表情短引用",
                validator=reference_validator("表情"),
            ),
            CommandParameter(
                "回复",
                "reply_ref",
                prompt_hint="当前可见的一条消息短引用",
                validator=reference_validator("回复"),
            ),
            _DELAY_PARAMETER,
            _INTERRUPTIBLE_PARAMETER,
            _MEMO_PARAMETER,
        ),
        terminal=True,
        send_kind="STICKER",
        usage_guidance=(
            "一个指令发送一个表情，可以重复同一引用。候选释义就是实际态度；可以跑题，但除非刻意制造反差，"
            "不要选与本轮意图相反的嘲讽、嫌弃、拒绝或敷衍表情。"
        ),
    ),
    CommandSpec(
        "发文件",
        "__send_file",
        "想发送当前已经完成的文件时使用。",
        (
            CommandParameter(
                "文件",
                "asset_ref",
                required=True,
                prompt_hint="当前可用的文件短引用",
                validator=reference_validator("文件"),
            ),
            CommandParameter(
                "回复",
                "reply_ref",
                prompt_hint="当前可见的一条消息短引用",
                validator=reference_validator("回复"),
            ),
            _DELAY_PARAMETER,
            _INTERRUPTIBLE_PARAMETER,
            _MEMO_PARAMETER,
        ),
        terminal=True,
        send_kind="FILE",
        usage_guidance=("这里只发送已经完成的文件；可以只发文件，也可以另发一条文字说明。"),
    ),
    CommandSpec(
        "撤回",
        "__retract",
        "已经发出后反悔、发错或想让刚发的内容只停留一会儿时使用。",
        (
            CommandParameter(
                "消息",
                "message_ref",
                prompt_hint="撤回当前现场里已有的消息时，填写那条消息的短引用",
                validator=reference_validator("消息"),
            ),
            CommandParameter(
                "本轮消息",
                "target_output_ordinal",
                prompt_hint="撤回本轮刚发出的内容时，填写它在本轮发送中的序号，从 1 开始",
                validator=integer_validator("本轮消息", minimum=1, maximum=10_000),
            ),
            _RETRACTION_DELAY_PARAMETER,
        ),
        terminal=True,
        send_kind="RETRACT",
        usage_guidance=(
            "[[消息]]与[[本轮消息]]必须且只能填写一个。撤回以前已有的消息时，把“撤回”放在"
            "本轮所有新发送之前；延迟从本轮开始计算。撤回本轮刚发出的内容时，先写发送指令，"
            "再紧接“撤回”；延迟表示那条内容实际发出后保留多久。"
        ),
    ),
    CommandSpec(
        "暂离",
        "__temporary_absence",
        "只有确实决定在当前会话里一段时间不看消息时使用；普通的一次不回复仍用“不说了”。",
        (
            CommandParameter(
                "原因",
                "reason",
                required=True,
                prompt_hint="为什么这段时间不看消息；这是角色自己的主观说明",
                identity_mode="template",
            ),
            CommandParameter(
                "大概多久",
                "time_expression",
                required=True,
                prompt_hint="能唯一确定到未来一分钟至二十四小时内的自然时间，例如“半小时后”",
            ),
        ),
        terminal=True,
        send_kind="ABSENCE",
        usage_guidance=(
            "它只影响当前会话，期间普通消息会保留原时间，等暂离结束后自然看到。"
            "定时事项到期会提前结束暂离。"
        ),
    ),
    CommandSpec(
        "不说了",
        "__silent",
        "这一次确实不想发任何内容，或者眼下正忙、没有必要回应时使用。",
        (),
        terminal=True,
        send_kind="SILENT",
        usage_guidance="若想稍后主动回来，先另设安排。",
    ),
)


__all__ = ["_MODEL_RESULT_VALUES", "_RESULT_FIELD_NAMES", "_TERMINAL_SPECS"]
