"""Typed storage boundaries used by AI runtime and administration."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, Protocol


class AIRepositoryPort(Protocol):
    async def create_ai_task(self, profile_id: str, task_type: str, **values: object) -> object: ...
    async def request_pause_ai_task(self, task_id: int, **values: object) -> object: ...
    async def resume_ai_task(self, task_id: int, **values: object) -> object: ...
    async def request_cancel_ai_task(self, task_id: int, **values: object) -> object: ...
    async def manual_retry_ai_task(self, task_id: int, **values: object) -> object: ...
    async def list_ai_manager_pauses(self) -> Sequence[Mapping[str, object]]: ...
    async def list_ai_backends(self) -> Sequence[Mapping[str, object]]: ...
    async def list_ai_api_models(self, **values: object) -> Sequence[Mapping[str, object]]: ...
    async def list_ai_capability_pool(self, capability: str) -> Sequence[Mapping[str, object]]: ...
    async def get_ai_task(self, task_id: int) -> Mapping[str, object] | None: ...
    async def create_ai_workflow(self, record: object) -> Mapping[str, object]: ...
    async def finish_ai_workflow(self, workflow_id: int, **values: object) -> object: ...
    async def start_ai_work_node(self, record: object) -> Mapping[str, object]: ...
    async def project_model_visible_message_ids(
        self,
        run_id: int,
        node_id: int,
        message_ids: Sequence[int],
        *,
        summary_ids: Sequence[int] = (),
        summary_coverage: Sequence[Sequence[int]] = (),
    ) -> object: ...
    async def finish_ai_work_node(self, node_id: int, **values: object) -> object: ...
    async def get_ai_work_node_by_model_invocation(
        self, invocation_id: str
    ) -> Mapping[str, object] | None: ...
    async def start_ai_provider_attempt(self, record: object) -> Mapping[str, object]: ...
    async def enrich_ai_provider_attempt(self, attempt_id: int, **values: object) -> object: ...
    async def mark_ai_provider_attempt_sent(self, attempt_id: int, **values: object) -> object: ...
    async def finish_ai_provider_attempt(self, attempt_id: int, **values: object) -> object: ...
    async def annotate_ai_provider_attempt(self, record: object) -> object: ...
    async def record_ai_work_event(self, record: object) -> object: ...
    async def record_ai_backend_health(self, record: object) -> object: ...
    async def record_ai_circuit_health(self, record: object) -> object: ...
    async def claim_ai_prompt_cache_capability(
        self, backend_id: str, **values: object
    ) -> Mapping[str, object]: ...
    async def observe_ai_prompt_cache_capability(
        self, backend_id: str, **values: object
    ) -> object: ...
    async def reject_ai_prompt_cache_capability(
        self, backend_id: str, **values: object
    ) -> object: ...
    async def request_ai_prompt_cache_reprobe(self, backend_id: str) -> object: ...


class DurableTaskRepositoryPort(Protocol):
    async def ensure_ai_task_workflow(self, task_id: int) -> Mapping[str, object] | None: ...
    async def finish_ai_workflow(self, workflow_id: int, **values: object) -> object: ...
    async def heartbeat_ai_task(self, task_id: int, **values: object) -> object: ...
    async def recover_expired_ai_tasks(self) -> object: ...
    async def claim_ai_tasks(self, **values: object) -> Sequence[Mapping[str, object]]: ...
    async def release_ai_task(self, task_id: int, **values: object) -> object: ...
    async def acknowledge_pause_ai_task(self, task_id: int, **values: object) -> object: ...
    async def acknowledge_cancel_ai_task(self, task_id: int, **values: object) -> object: ...
    async def defer_ai_task(self, task_id: int, **values: object) -> object: ...
    async def complete_ai_task(self, task_id: int, **values: object) -> object: ...
    async def fail_ai_task(self, task_id: int, **values: object) -> object: ...
    async def get_ai_task(self, task_id: int) -> Mapping[str, object] | None: ...
    async def record_ai_backend_success(self, backend_id: str) -> object: ...
    async def record_ai_backend_failure(self, backend_id: str, **values: object) -> object: ...
    async def cleanup_ai_task_history(self) -> Mapping[str, object]: ...
    async def create_ai_task(self, profile_id: str, task_type: str, **values: object) -> object: ...
    async def request_pause_ai_task(self, task_id: int, **values: object) -> object: ...
    async def resume_ai_task(self, task_id: int, **values: object) -> object: ...
    async def request_cancel_ai_task(self, task_id: int, **values: object) -> object: ...
    async def manual_retry_ai_task(self, task_id: int, **values: object) -> object: ...


class AIConfigurationRepositoryPort(Protocol):
    """Persistence required to edit packages, models, backends and pools."""

    async def archive_ai_api_model(self, *values: object, **named: object) -> object: ...
    async def archive_ai_api_package(self, *values: object, **named: object) -> object: ...
    async def get_ai_api_model(self, *values: object, **named: object) -> object: ...
    async def get_ai_api_package(self, *values: object, **named: object) -> object: ...
    async def get_ai_backend(self, *values: object, **named: object) -> object: ...
    async def list_ai_api_models(self, *values: object, **named: object) -> object: ...
    async def list_ai_api_packages(self, *values: object, **named: object) -> object: ...
    async def list_ai_backends(self, *values: object, **named: object) -> object: ...
    async def list_ai_capability_pool(self, *values: object, **named: object) -> object: ...
    async def reset_ai_api_package_health(self, *values: object, **named: object) -> object: ...
    async def set_ai_api_model_enabled(self, *values: object, **named: object) -> object: ...
    async def set_ai_api_package_enabled(self, *values: object, **named: object) -> object: ...
    async def upsert_ai_api_model(self, *values: object, **named: object) -> object: ...
    async def upsert_ai_api_package(self, *values: object, **named: object) -> object: ...
    async def upsert_ai_backend(self, *values: object, **named: object) -> object: ...
    async def upsert_ai_capability_pool(self, *values: object, **named: object) -> object: ...
    async def list_ai_prompt_cache_capabilities(
        self, *values: object, **named: object
    ) -> object: ...
    async def invalidate_ai_prompt_cache_capabilities(
        self, *values: object, **named: object
    ) -> object: ...
    async def request_ai_prompt_cache_reprobe(self, *values: object, **named: object) -> object: ...


class AIAdminQueryRepositoryPort(Protocol):
    """Durable-task and routing read model used by the AI admin facade."""

    async def get_ai_api_model(
        self, *values: object, **named: object
    ) -> Mapping[str, Any] | None: ...
    async def get_ai_api_package(
        self, *values: object, **named: object
    ) -> Mapping[str, Any] | None: ...
    async def get_ai_backend(
        self, *values: object, **named: object
    ) -> Mapping[str, Any] | None: ...
    async def get_ai_task(self, *values: object, **named: object) -> Mapping[str, Any] | None: ...
    async def list_ai_backends(
        self, *values: object, **named: object
    ) -> list[Mapping[str, Any]]: ...
    async def list_ai_capability_pool(
        self, *values: object, **named: object
    ) -> list[Mapping[str, Any]]: ...
    async def list_ai_workflow_summaries(
        self, *values: object, **named: object
    ) -> list[Mapping[str, Any]]: ...
    async def list_ai_work_filter_values(
        self, *values: object, **named: object
    ) -> Mapping[str, list[str]]: ...
    async def get_ai_workflow_by_ref(
        self, *values: object, **named: object
    ) -> Mapping[str, Any] | None: ...
    async def list_ai_work_nodes(
        self, *values: object, **named: object
    ) -> list[Mapping[str, Any]]: ...
    async def list_ai_provider_attempts(
        self, *values: object, **named: object
    ) -> list[Mapping[str, Any]]: ...
    async def get_ai_provider_attempt_by_ref(
        self, *values: object, **named: object
    ) -> Mapping[str, Any] | None: ...
    async def list_ai_work_events(
        self, *values: object, **named: object
    ) -> list[Mapping[str, Any]]: ...
    async def list_ai_workflow_deliveries(
        self, *values: object, **named: object
    ) -> list[Mapping[str, Any]]: ...
    async def list_ai_manager_pauses(
        self, *values: object, **named: object
    ) -> list[Mapping[str, Any]]: ...
    async def list_ai_task_attempts(
        self, *values: object, **named: object
    ) -> list[Mapping[str, Any]]: ...
    async def list_ai_task_audit(
        self, *values: object, **named: object
    ) -> list[Mapping[str, Any]]: ...
    async def list_ai_tasks(self, *values: object, **named: object) -> list[Mapping[str, Any]]: ...
    async def list_ai_prompt_cache_capabilities(
        self, *values: object, **named: object
    ) -> list[Mapping[str, Any]]: ...
    async def set_ai_manager_pause(self, *values: object, **named: object) -> Mapping[str, Any]: ...
    async def upsert_ai_capability_pool(
        self, *values: object, **named: object
    ) -> Mapping[str, Any]: ...


__all__ = [
    "AIRepositoryPort",
    "AIAdminQueryRepositoryPort",
    "AIConfigurationRepositoryPort",
    "DurableTaskRepositoryPort",
]
