"""Persistence boundary for delivery policy and QPM adapters."""

from datetime import datetime
from typing import Any, Protocol

from ...contracts.models import (
    MessageRetractionAction,
    OutboxItem,
    PlatformMessageFragment,
)


class DeliveryRepositoryPort(Protocol):
    async def apply_inbound_admission(self, *args: object, **kwargs: object) -> Any: ...
    async def renew_inbound_admission(self, *args: object, **kwargs: object) -> bool: ...
    async def complete_inbound_admission(self, *args: object, **kwargs: object) -> bool: ...
    async def acquire_foreground_lease(self, *args: object, **kwargs: object) -> str: ...
    async def renew_foreground_lease(self, *args: object, **kwargs: object) -> bool: ...
    async def release_foreground_lease(self, *args: object, **kwargs: object) -> bool: ...
    async def delete_instance_delivery_override(self, *args: object, **kwargs: object) -> Any: ...
    async def get_instance_delivery_override(self, *args: object, **kwargs: object) -> Any: ...
    async def resolve_expression_pacing_policy(self, *args: object, **kwargs: object) -> Any: ...
    async def reserve_expression_send_permit(self, *args: object, **kwargs: object) -> Any: ...
    async def begin_dispatch_platform_send_permit(self, *args: object, **kwargs: object) -> Any: ...
    async def begin_group_expression_send_permit(self, *args: object, **kwargs: object) -> Any: ...
    async def prepare_group_expression_dispatch(self, *args: object, **kwargs: object) -> Any: ...
    async def resolve_group_window_if_no_deliverable(
        self, *args: object, **kwargs: object
    ) -> Any: ...
    async def fail_platform_send_permit_before_dispatch(
        self, *args: object, **kwargs: object
    ) -> Any: ...
    async def mark_platform_send_permit_attempted_unknown(
        self, *args: object, **kwargs: object
    ) -> Any: ...
    async def release_platform_send_permits(self, *args: object, **kwargs: object) -> Any: ...
    async def renew_platform_send_permits(self, *args: object, **kwargs: object) -> Any: ...
    async def reserve_platform_send_permits(self, *args: object, **kwargs: object) -> Any: ...
    async def resize_platform_send_permits(self, *args: object, **kwargs: object) -> Any: ...
    async def snapshot_platform_send_qpm(self, *args: object, **kwargs: object) -> Any: ...
    async def upsert_instance_delivery_override(self, *args: object, **kwargs: object) -> Any: ...
    async def enqueue_instance_outbox(self, *args: object, **kwargs: object) -> Any: ...
    async def get_instance_outbox(self, *args: object, **kwargs: object) -> Any: ...
    async def list_instance_outbox(self, *args: object, **kwargs: object) -> Any: ...
    async def list_profile_recent_failed_outbox(
        self,
        profile_id: str,
        *,
        limit_per_instance: int = 20,
    ) -> list[OutboxItem]: ...
    async def list_due_expression_outbox(
        self, *args: object, **kwargs: object
    ) -> list[OutboxItem]: ...
    async def next_expression_outbox_due_at(self) -> datetime | None: ...
    async def get_expression_foreground_barrier(
        self, profile_id: str, instance_id: str, activity_epoch: int
    ) -> dict[str, Any]: ...


class DeliveryPolicyPort(Protocol):
    async def get_delivery_policy(self, *args: object, **kwargs: object) -> object: ...
    async def update_delivery_policy(self, *args: object, **kwargs: object) -> object: ...


class OutboxRepositoryPort(Protocol):
    async def resolve_expression_pacing_policy(self, *args: object, **kwargs: object) -> object: ...
    async def list_due_retraction_actions(
        self, *, now: datetime | None = None, limit: int = 100
    ) -> list[MessageRetractionAction]: ...
    async def next_retraction_action_due_at(self) -> datetime | None: ...
    async def recover_sending_retraction_actions(self) -> int: ...
    async def claim_retraction_action(self, *args: object, **kwargs: object) -> object: ...
    async def claim_retraction_fragment(self, *args: object, **kwargs: object) -> bool: ...
    async def settle_retraction_fragment(self, *args: object, **kwargs: object) -> bool: ...
    async def release_retraction_action(self, *args: object, **kwargs: object) -> bool: ...
    async def finalize_retraction_action(self, *args: object, **kwargs: object) -> object: ...
    async def resolve_retraction_target_fragments(
        self, *args: object, **kwargs: object
    ) -> list[PlatformMessageFragment]: ...
    async def transition_retraction_action(self, *args: object, **kwargs: object) -> object: ...
    async def advance_activity_and_interrupt_expressions(
        self, profile_id: str, instance_id: str, inbound_message_id: int
    ) -> int: ...
    async def advance_group_held_activity(self, profile_id: str, instance_id: str) -> int: ...
    async def begin_instance_outbox_dispatch(self, *args: object, **kwargs: object) -> object: ...
    async def cancel_unstarted_expression_items(
        self, *args: object, **kwargs: object
    ) -> object: ...
    async def defer_expression_batch_suffix(self, *args: object, **kwargs: object) -> object: ...
    async def get_expression_batch(self, *args: object, **kwargs: object) -> object: ...
    async def list_due_expression_outbox(
        self, *args: object, **kwargs: object
    ) -> list[OutboxItem]: ...
    async def next_expression_outbox_due_at(self) -> datetime | None: ...
    async def recover_pending_expression_interruptions(self, *, limit: int = 100) -> int: ...
    async def get_expression_foreground_barrier(
        self, profile_id: str, instance_id: str, activity_epoch: int
    ) -> dict[str, Any]: ...
    async def allows_preserved_expression_dispatch(
        self, profile_id: str, instance_id: str, outbox_id: int
    ) -> bool: ...
    async def list_expression_batches(self, *args: object, **kwargs: object) -> object: ...
    async def reserve_expression_send_permit(self, *args: object, **kwargs: object) -> object: ...
    async def begin_dispatch_platform_send_permit(
        self, *args: object, **kwargs: object
    ) -> object: ...
    async def begin_group_expression_send_permit(
        self, *args: object, **kwargs: object
    ) -> object: ...
    async def prepare_group_expression_dispatch(
        self, *args: object, **kwargs: object
    ) -> object: ...
    async def resolve_group_window_if_no_deliverable(
        self, *args: object, **kwargs: object
    ) -> object: ...
    async def mark_platform_send_permit_attempted_unknown(
        self, *args: object, **kwargs: object
    ) -> object: ...
    async def fail_platform_send_permit_before_dispatch(
        self, *args: object, **kwargs: object
    ) -> object: ...
    async def list_instance_outbox(self, *args: object, **kwargs: object) -> object: ...
    async def get_instance_outbox(self, *args: object, **kwargs: object) -> object: ...
    async def get_instance_outbox_by_idempotency_key(
        self, *args: object, **kwargs: object
    ) -> object: ...
    async def claim_instance_outbox(self, *args: object, **kwargs: object) -> object: ...
    async def transition_instance_outbox(self, *args: object, **kwargs: object) -> object: ...


class VoiceArtifactRepositoryPort(Protocol):
    async def register_outbox_voice_artifact(self, *args: object, **kwargs: object) -> object: ...
    async def list_outbox_voice_artifacts(self, *args: object, **kwargs: object) -> object: ...
    async def schedule_outbox_voice_artifact_cleanup(
        self, *args: object, **kwargs: object
    ) -> object: ...
    async def complete_outbox_voice_artifact_cleanup(
        self, *args: object, **kwargs: object
    ) -> bool: ...
    async def persist_outbox_voice_text_fallback(self, *args: object, **kwargs: object) -> bool: ...


class VoiceOutboxRepositoryPort(
    OutboxRepositoryPort,
    VoiceArtifactRepositoryPort,
    Protocol,
):
    """Runner composition requiring both ordinary Outbox and voice storage."""


class OutboxSettlementPort(Protocol):
    async def finalize_foreground_delivery(self, *args: object, **kwargs: object) -> object: ...
    async def finalize_instance_outbox_delivery(
        self, *args: object, **kwargs: object
    ) -> object: ...
    async def publish_context_backup(self) -> str | None: ...


class InstanceWakeupRepositoryPort(Protocol):
    async def claim_due_instance_wakeups(self, *args: object, **kwargs: object) -> object: ...
    async def complete_instance_wakeup(self, *args: object, **kwargs: object) -> object: ...
    async def retry_instance_wakeup(self, *args: object, **kwargs: object) -> object: ...
    async def fail_instance_wakeup(self, *args: object, **kwargs: object) -> object: ...


__all__ = [
    "DeliveryRepositoryPort",
    "DeliveryPolicyPort",
    "OutboxRepositoryPort",
    "OutboxSettlementPort",
    "InstanceWakeupRepositoryPort",
    "VoiceArtifactRepositoryPort",
    "VoiceOutboxRepositoryPort",
]
