"""Persistence and collaboration boundaries for the knowledge feature."""

from dataclasses import dataclass
from typing import Any, Protocol


@dataclass(frozen=True, slots=True)
class KnowledgeWorldInfoOverlayHit:
    """The small, product-safe projection shared with the WorldInfo facade."""

    record_id: int
    content: str
    score: float


class KnowledgeWorldInfoOverlayPort(Protocol):
    async def query_world_info_overlay(
        self,
        profile_id: str,
        instance_id: str,
        query: str,
        *,
        limit: int = 5,
    ) -> list[KnowledgeWorldInfoOverlayHit]: ...


class KnowledgeRepositoryPort(Protocol):
    async def commit_knowledge_batch(self, *args: object, **kwargs: object) -> Any: ...
    async def get_knowledge_status(self, *args: object, **kwargs: object) -> Any: ...
    async def list_knowledge_audit(self, *args: object, **kwargs: object) -> Any: ...
    async def list_knowledge_batches(self, *args: object, **kwargs: object) -> Any: ...
    async def list_memories(self, *args: object, **kwargs: object) -> Any: ...
    async def list_knowledge_facts(self, *args: object, **kwargs: object) -> Any: ...
    async def list_active_memories(self, *args: object, **kwargs: object) -> Any: ...
    async def list_context_memories(self, *args: object, **kwargs: object) -> Any: ...
    async def prepare_knowledge_batch(self, *args: object, **kwargs: object) -> Any: ...
    async def refresh_knowledge_task(self, *args: object, **kwargs: object) -> Any: ...
    async def search_memories(self, *args: object, **kwargs: object) -> Any: ...
    async def search_knowledge_facts(self, *args: object, **kwargs: object) -> Any: ...
    async def settle_empty_knowledge_task(self, *args: object, **kwargs: object) -> Any: ...
