"""Narrow persistence ports for contact, gates, intents, and user world seeds."""

from typing import Any, Protocol


class StateGateRepositoryPort(Protocol):
    async def create_or_append_deferred_message_batch(
        self, *args: object, **kwargs: object
    ) -> Any: ...
    async def append_or_merge_deferred_gate_message(
        self, *args: object, **kwargs: object
    ) -> Any: ...
    async def claim_deferred_gate_batch_for_foreground(
        self, *args: object, **kwargs: object
    ) -> Any: ...
    async def claim_due_deferred_gate_batches(self, *args: object, **kwargs: object) -> Any: ...
    async def get_deferred_message_batch(self, *args: object, **kwargs: object) -> Any: ...
    async def get_state_gate_policy(self, *args: object, **kwargs: object) -> Any: ...
    async def update_state_gate_policy(self, *args: object, **kwargs: object) -> Any: ...
    async def resolve_state_gate_policy(self, *args: object, **kwargs: object) -> Any: ...
    async def get_state_gate_snapshot(self, *args: object, **kwargs: object) -> Any: ...
    async def get_instance_state_gate_override(self, *args: object, **kwargs: object) -> Any: ...
    async def upsert_instance_state_gate_override(self, *args: object, **kwargs: object) -> Any: ...
    async def delete_instance_state_gate_override(self, *args: object, **kwargs: object) -> Any: ...
    async def get_state_message_gate_policy(self, *args: object, **kwargs: object) -> Any: ...
    async def get_state_message_gate_snapshot(self, *args: object, **kwargs: object) -> Any: ...
    async def release_deferred_gate_batch(self, *args: object, **kwargs: object) -> Any: ...
    async def renew_deferred_gate_batch_lease(self, *args: object, **kwargs: object) -> Any: ...
    async def resolve_deferred_gate_batch(self, *args: object, **kwargs: object) -> Any: ...
    async def ensure_expired_temporary_absence_wakeups(
        self, *args: object, **kwargs: object
    ) -> Any: ...
    async def prepare_temporary_absence_expiry(self, *args: object, **kwargs: object) -> Any: ...
    async def finalize_temporary_absence_expiry(self, *args: object, **kwargs: object) -> Any: ...
    async def interrupt_temporary_absence_for_timer(
        self, *args: object, **kwargs: object
    ) -> Any: ...


class SchedulerTimelinePort(Protocol):
    async def resolve_contact_policy(self, *args: object, **kwargs: object) -> Any: ...
    async def mark_latest_contact_attempt_answered(
        self, *args: object, **kwargs: object
    ) -> Any: ...
    async def settle_contact_evidence(self, *args: object, **kwargs: object) -> Any: ...
    async def finalize_contact_attempt(self, *args: object, **kwargs: object) -> Any: ...
    async def reconcile_failed_contact_task_handoffs(
        self, *args: object, **kwargs: object
    ) -> Any: ...
    async def list_pending_contact_task_handoffs(self, *args: object, **kwargs: object) -> Any: ...
    async def publish_contact_task_handoff(self, *args: object, **kwargs: object) -> Any: ...
    async def cancel_unpublished_contact_task(self, *args: object, **kwargs: object) -> Any: ...
    async def cancel_pending_contact_task_handoff(self, *args: object, **kwargs: object) -> Any: ...


class TimelineAdminRepositoryPort(Protocol):
    async def bind_instance_run_workflow(self, *args: object, **kwargs: object) -> Any: ...
    async def get_instance_run_workflow(self, *args: object, **kwargs: object) -> Any: ...
    async def get_world_definition(self, *args: object, **kwargs: object) -> Any: ...
    async def update_world_definition(self, *args: object, **kwargs: object) -> Any: ...
    async def list_world_lore_entries(self, *args: object, **kwargs: object) -> Any: ...
    async def get_world_lore_entry(self, *args: object, **kwargs: object) -> Any: ...
    async def create_world_lore_entry(self, *args: object, **kwargs: object) -> Any: ...
    async def update_world_lore_entry(self, *args: object, **kwargs: object) -> Any: ...
    async def delete_world_lore_entry(self, *args: object, **kwargs: object) -> Any: ...
    async def list_creative_boundaries(self, *args: object, **kwargs: object) -> Any: ...
    async def create_creative_boundary(self, *args: object, **kwargs: object) -> Any: ...
    async def update_creative_boundary(self, *args: object, **kwargs: object) -> Any: ...
    async def delete_creative_boundary(self, *args: object, **kwargs: object) -> Any: ...
    async def list_instance_wakeups(self, *args: object, **kwargs: object) -> Any: ...
    async def delete_instance_delivery_override(self, *args: object, **kwargs: object) -> Any: ...
    async def get_instance_delivery_override(self, *args: object, **kwargs: object) -> Any: ...
    async def get_profile_timezone(self, *args: object, **kwargs: object) -> Any: ...
    async def get_delivery_policy(self, *args: object, **kwargs: object) -> Any: ...
    async def update_delivery_policy(self, *args: object, **kwargs: object) -> Any: ...
    async def get_contact_policy(self, *args: object, **kwargs: object) -> Any: ...
    async def update_contact_policy(self, *args: object, **kwargs: object) -> Any: ...
    async def configure_quick_setup_contact(self, *args: object, **kwargs: object) -> Any: ...
    async def resolve_contact_policy(self, *args: object, **kwargs: object) -> Any: ...
    async def resolve_expression_pacing_policy(self, *args: object, **kwargs: object) -> Any: ...
    async def upsert_instance_delivery_override(self, *args: object, **kwargs: object) -> Any: ...
    async def get_instance_contact_override(self, *args: object, **kwargs: object) -> Any: ...
    async def upsert_instance_contact_override(self, *args: object, **kwargs: object) -> Any: ...
    async def delete_instance_contact_override(self, *args: object, **kwargs: object) -> Any: ...
    async def get_platform_contact_policy(self, *args: object, **kwargs: object) -> Any: ...
    async def upsert_platform_contact_policy(self, *args: object, **kwargs: object) -> Any: ...
    async def delete_platform_contact_policy(self, *args: object, **kwargs: object) -> Any: ...
    async def apply_character_intent_mutations(self, *args: object, **kwargs: object) -> Any: ...
    async def delete_character_intent(self, *args: object, **kwargs: object) -> Any: ...
    async def get_character_intent(self, *args: object, **kwargs: object) -> Any: ...


class TimelineRepositoryPort(
    StateGateRepositoryPort,
    SchedulerTimelinePort,
    TimelineAdminRepositoryPort,
    Protocol,
):
    """Complete persistence boundary used by timeline composition roots."""


__all__ = [
    "SchedulerTimelinePort",
    "StateGateRepositoryPort",
    "TimelineAdminRepositoryPort",
    "TimelineRepositoryPort",
]
